name=input("Enter your Name:")
sap_id=input("Enter your SAP ID:")
dob=input("Enter your Date of Birth:")
address=input("Enter your address:")
program=input("Enter your learning program:")
sem=input("Enter you semester:")
print("Student details:")
print("NAME: ",name)
print("SAP ID: ",sap_id)
print("DATE OF BIRTH: ",dob)
print("ADDRESS: ",address)
print("PROGRAM ENTERED: ",program)
print("SEMESTER: ",sem)
